baseURL: "https://sahanasubramanyam.github.io/" 
title: Sahana Subramanyam
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    #twitter: pmichaillat
    instagram: eyeflies.art

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: Art
          url: /art/
          weight: 2
        #- name: Design
          #url: /design/
          #weight: 3
        - name: Tags
          url: /tags/
          weight: 5     
        #- name: Newsletter
          #url: https://pmichaillat.substack.com
          #weight: 4

params:
    description: "I am a second year Economics PhD student at Stanford University. My research interests are development, labor and behavioral economics."
    author: Sahana Subramanyam
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sahana Subramanyam
          subtitle: "I am a second year Economics PhD student at Stanford University. My research interests are development, labor and behavioral economics."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Sahana Subramanyam
          buttons:
            - name: Research
              url: /research/
            - name: Art
              url: /art/
            #- name: Design
              #url: /design/
            #- name: Newsletter
              #url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:sahana.subramanyam@gmail.com
        #- name: Location
          #url: /location/
        #- name: Office Hours
          #url: /officehours/
        #- name: Google Scholar
          #url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: YouTube
          #url: https://www.youtube.com/@pmichaillat
        #- name: GitHub
          #url: https://github.com/pmichaillat?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Sahana Subramanyam"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
